# permissions for end users to edit injectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: injector-editor-role
rules:
- apiGroups:
  - injector.dev.digitalnerd
  resources:
  - injectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - injector.dev.digitalnerd
  resources:
  - injectors/status
  verbs:
  - get
